
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Role
 * 
 */
export type Role = Prisma.RoleModel
/**
 * Model Permission
 * 
 */
export type Permission = Prisma.PermissionModel
/**
 * Model Customer
 * 
 */
export type Customer = Prisma.CustomerModel
/**
 * Model ReceivablePayment
 * 
 */
export type ReceivablePayment = Prisma.ReceivablePaymentModel
/**
 * Model Address
 * 
 */
export type Address = Prisma.AddressModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model Brand
 * 
 */
export type Brand = Prisma.BrandModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model ProductImage
 * 
 */
export type ProductImage = Prisma.ProductImageModel
/**
 * Model ProductSpec
 * 
 */
export type ProductSpec = Prisma.ProductSpecModel
/**
 * Model ProductTag
 * 
 */
export type ProductTag = Prisma.ProductTagModel
/**
 * Model CartItem
 * 
 */
export type CartItem = Prisma.CartItemModel
/**
 * Model WishlistItem
 * 
 */
export type WishlistItem = Prisma.WishlistItemModel
/**
 * Model Order
 * 
 */
export type Order = Prisma.OrderModel
/**
 * Model OrderItem
 * 
 */
export type OrderItem = Prisma.OrderItemModel
/**
 * Model OrderStatusHistory
 * 
 */
export type OrderStatusHistory = Prisma.OrderStatusHistoryModel
/**
 * Model Payment
 * 
 */
export type Payment = Prisma.PaymentModel
/**
 * Model Coupon
 * 
 */
export type Coupon = Prisma.CouponModel
/**
 * Model AuditLog
 * 
 */
export type AuditLog = Prisma.AuditLogModel
/**
 * Model Setting
 * 
 */
export type Setting = Prisma.SettingModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Supplier
 * 
 */
export type Supplier = Prisma.SupplierModel
/**
 * Model Purchase
 * 
 */
export type Purchase = Prisma.PurchaseModel
/**
 * Model PurchaseItem
 * 
 */
export type PurchaseItem = Prisma.PurchaseItemModel
/**
 * Model StockMovement
 * 
 */
export type StockMovement = Prisma.StockMovementModel
/**
 * Model ReturnOrder
 * 
 */
export type ReturnOrder = Prisma.ReturnOrderModel
/**
 * Model ReturnItem
 * 
 */
export type ReturnItem = Prisma.ReturnItemModel
/**
 * Model CashSession
 * 
 */
export type CashSession = Prisma.CashSessionModel
/**
 * Model CashMovement
 * 
 */
export type CashMovement = Prisma.CashMovementModel
