
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Customer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Customer
 * 
 */
export type CustomerModel = runtime.Types.Result.DefaultSelection<Prisma.$CustomerPayload>

export type AggregateCustomer = {
  _count: CustomerCountAggregateOutputType | null
  _avg: CustomerAvgAggregateOutputType | null
  _sum: CustomerSumAggregateOutputType | null
  _min: CustomerMinAggregateOutputType | null
  _max: CustomerMaxAggregateOutputType | null
}

export type CustomerAvgAggregateOutputType = {
  totalPurchases: number | null
  balance: number | null
}

export type CustomerSumAggregateOutputType = {
  totalPurchases: number | null
  balance: number | null
}

export type CustomerMinAggregateOutputType = {
  id: string | null
  userId: string | null
  name: string | null
  lastname: string | null
  document: string | null
  phone: string | null
  whatsapp: string | null
  email: string | null
  city: string | null
  department: string | null
  address: string | null
  notes: string | null
  totalPurchases: number | null
  balance: number | null
  isBlocked: boolean | null
  blockedReason: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CustomerMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  name: string | null
  lastname: string | null
  document: string | null
  phone: string | null
  whatsapp: string | null
  email: string | null
  city: string | null
  department: string | null
  address: string | null
  notes: string | null
  totalPurchases: number | null
  balance: number | null
  isBlocked: boolean | null
  blockedReason: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CustomerCountAggregateOutputType = {
  id: number
  userId: number
  name: number
  lastname: number
  document: number
  phone: number
  whatsapp: number
  email: number
  city: number
  department: number
  address: number
  notes: number
  totalPurchases: number
  balance: number
  isBlocked: number
  blockedReason: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CustomerAvgAggregateInputType = {
  totalPurchases?: true
  balance?: true
}

export type CustomerSumAggregateInputType = {
  totalPurchases?: true
  balance?: true
}

export type CustomerMinAggregateInputType = {
  id?: true
  userId?: true
  name?: true
  lastname?: true
  document?: true
  phone?: true
  whatsapp?: true
  email?: true
  city?: true
  department?: true
  address?: true
  notes?: true
  totalPurchases?: true
  balance?: true
  isBlocked?: true
  blockedReason?: true
  createdAt?: true
  updatedAt?: true
}

export type CustomerMaxAggregateInputType = {
  id?: true
  userId?: true
  name?: true
  lastname?: true
  document?: true
  phone?: true
  whatsapp?: true
  email?: true
  city?: true
  department?: true
  address?: true
  notes?: true
  totalPurchases?: true
  balance?: true
  isBlocked?: true
  blockedReason?: true
  createdAt?: true
  updatedAt?: true
}

export type CustomerCountAggregateInputType = {
  id?: true
  userId?: true
  name?: true
  lastname?: true
  document?: true
  phone?: true
  whatsapp?: true
  email?: true
  city?: true
  department?: true
  address?: true
  notes?: true
  totalPurchases?: true
  balance?: true
  isBlocked?: true
  blockedReason?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CustomerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Customer to aggregate.
   */
  where?: Prisma.CustomerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Customers to fetch.
   */
  orderBy?: Prisma.CustomerOrderByWithRelationInput | Prisma.CustomerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CustomerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Customers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Customers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Customers
  **/
  _count?: true | CustomerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CustomerAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CustomerSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CustomerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CustomerMaxAggregateInputType
}

export type GetCustomerAggregateType<T extends CustomerAggregateArgs> = {
      [P in keyof T & keyof AggregateCustomer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCustomer[P]>
    : Prisma.GetScalarType<T[P], AggregateCustomer[P]>
}




export type CustomerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CustomerWhereInput
  orderBy?: Prisma.CustomerOrderByWithAggregationInput | Prisma.CustomerOrderByWithAggregationInput[]
  by: Prisma.CustomerScalarFieldEnum[] | Prisma.CustomerScalarFieldEnum
  having?: Prisma.CustomerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CustomerCountAggregateInputType | true
  _avg?: CustomerAvgAggregateInputType
  _sum?: CustomerSumAggregateInputType
  _min?: CustomerMinAggregateInputType
  _max?: CustomerMaxAggregateInputType
}

export type CustomerGroupByOutputType = {
  id: string
  userId: string
  name: string
  lastname: string
  document: string
  phone: string
  whatsapp: string | null
  email: string
  city: string | null
  department: string | null
  address: string | null
  notes: string | null
  totalPurchases: number
  balance: number
  isBlocked: boolean
  blockedReason: string | null
  createdAt: Date
  updatedAt: Date
  _count: CustomerCountAggregateOutputType | null
  _avg: CustomerAvgAggregateOutputType | null
  _sum: CustomerSumAggregateOutputType | null
  _min: CustomerMinAggregateOutputType | null
  _max: CustomerMaxAggregateOutputType | null
}

export type GetCustomerGroupByPayload<T extends CustomerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CustomerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CustomerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CustomerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CustomerGroupByOutputType[P]>
      }
    >
  >



export type CustomerWhereInput = {
  AND?: Prisma.CustomerWhereInput | Prisma.CustomerWhereInput[]
  OR?: Prisma.CustomerWhereInput[]
  NOT?: Prisma.CustomerWhereInput | Prisma.CustomerWhereInput[]
  id?: Prisma.StringFilter<"Customer"> | string
  userId?: Prisma.StringFilter<"Customer"> | string
  name?: Prisma.StringFilter<"Customer"> | string
  lastname?: Prisma.StringFilter<"Customer"> | string
  document?: Prisma.StringFilter<"Customer"> | string
  phone?: Prisma.StringFilter<"Customer"> | string
  whatsapp?: Prisma.StringNullableFilter<"Customer"> | string | null
  email?: Prisma.StringFilter<"Customer"> | string
  city?: Prisma.StringNullableFilter<"Customer"> | string | null
  department?: Prisma.StringNullableFilter<"Customer"> | string | null
  address?: Prisma.StringNullableFilter<"Customer"> | string | null
  notes?: Prisma.StringNullableFilter<"Customer"> | string | null
  totalPurchases?: Prisma.IntFilter<"Customer"> | number
  balance?: Prisma.FloatFilter<"Customer"> | number
  isBlocked?: Prisma.BoolFilter<"Customer"> | boolean
  blockedReason?: Prisma.StringNullableFilter<"Customer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Customer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Customer"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  orders?: Prisma.OrderListRelationFilter
  receivablePayments?: Prisma.ReceivablePaymentListRelationFilter
  returns?: Prisma.ReturnOrderListRelationFilter
}

export type CustomerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  lastname?: Prisma.SortOrder
  document?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  whatsapp?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrder
  city?: Prisma.SortOrderInput | Prisma.SortOrder
  department?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  totalPurchases?: Prisma.SortOrder
  balance?: Prisma.SortOrder
  isBlocked?: Prisma.SortOrder
  blockedReason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  orders?: Prisma.OrderOrderByRelationAggregateInput
  receivablePayments?: Prisma.ReceivablePaymentOrderByRelationAggregateInput
  returns?: Prisma.ReturnOrderOrderByRelationAggregateInput
  _relevance?: Prisma.CustomerOrderByRelevanceInput
}

export type CustomerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  AND?: Prisma.CustomerWhereInput | Prisma.CustomerWhereInput[]
  OR?: Prisma.CustomerWhereInput[]
  NOT?: Prisma.CustomerWhereInput | Prisma.CustomerWhereInput[]
  name?: Prisma.StringFilter<"Customer"> | string
  lastname?: Prisma.StringFilter<"Customer"> | string
  document?: Prisma.StringFilter<"Customer"> | string
  phone?: Prisma.StringFilter<"Customer"> | string
  whatsapp?: Prisma.StringNullableFilter<"Customer"> | string | null
  email?: Prisma.StringFilter<"Customer"> | string
  city?: Prisma.StringNullableFilter<"Customer"> | string | null
  department?: Prisma.StringNullableFilter<"Customer"> | string | null
  address?: Prisma.StringNullableFilter<"Customer"> | string | null
  notes?: Prisma.StringNullableFilter<"Customer"> | string | null
  totalPurchases?: Prisma.IntFilter<"Customer"> | number
  balance?: Prisma.FloatFilter<"Customer"> | number
  isBlocked?: Prisma.BoolFilter<"Customer"> | boolean
  blockedReason?: Prisma.StringNullableFilter<"Customer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Customer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Customer"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  orders?: Prisma.OrderListRelationFilter
  receivablePayments?: Prisma.ReceivablePaymentListRelationFilter
  returns?: Prisma.ReturnOrderListRelationFilter
}, "id" | "userId">

export type CustomerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  lastname?: Prisma.SortOrder
  document?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  whatsapp?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrder
  city?: Prisma.SortOrderInput | Prisma.SortOrder
  department?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  totalPurchases?: Prisma.SortOrder
  balance?: Prisma.SortOrder
  isBlocked?: Prisma.SortOrder
  blockedReason?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CustomerCountOrderByAggregateInput
  _avg?: Prisma.CustomerAvgOrderByAggregateInput
  _max?: Prisma.CustomerMaxOrderByAggregateInput
  _min?: Prisma.CustomerMinOrderByAggregateInput
  _sum?: Prisma.CustomerSumOrderByAggregateInput
}

export type CustomerScalarWhereWithAggregatesInput = {
  AND?: Prisma.CustomerScalarWhereWithAggregatesInput | Prisma.CustomerScalarWhereWithAggregatesInput[]
  OR?: Prisma.CustomerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CustomerScalarWhereWithAggregatesInput | Prisma.CustomerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Customer"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Customer"> | string
  name?: Prisma.StringWithAggregatesFilter<"Customer"> | string
  lastname?: Prisma.StringWithAggregatesFilter<"Customer"> | string
  document?: Prisma.StringWithAggregatesFilter<"Customer"> | string
  phone?: Prisma.StringWithAggregatesFilter<"Customer"> | string
  whatsapp?: Prisma.StringNullableWithAggregatesFilter<"Customer"> | string | null
  email?: Prisma.StringWithAggregatesFilter<"Customer"> | string
  city?: Prisma.StringNullableWithAggregatesFilter<"Customer"> | string | null
  department?: Prisma.StringNullableWithAggregatesFilter<"Customer"> | string | null
  address?: Prisma.StringNullableWithAggregatesFilter<"Customer"> | string | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"Customer"> | string | null
  totalPurchases?: Prisma.IntWithAggregatesFilter<"Customer"> | number
  balance?: Prisma.FloatWithAggregatesFilter<"Customer"> | number
  isBlocked?: Prisma.BoolWithAggregatesFilter<"Customer"> | boolean
  blockedReason?: Prisma.StringNullableWithAggregatesFilter<"Customer"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Customer"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Customer"> | Date | string
}

export type CustomerCreateInput = {
  id?: string
  name: string
  lastname: string
  document: string
  phone: string
  whatsapp?: string | null
  email: string
  city?: string | null
  department?: string | null
  address?: string | null
  notes?: string | null
  totalPurchases?: number
  balance?: number
  isBlocked?: boolean
  blockedReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutCustomerProfileInput
  orders?: Prisma.OrderCreateNestedManyWithoutCustomerInput
  receivablePayments?: Prisma.ReceivablePaymentCreateNestedManyWithoutCustomerInput
  returns?: Prisma.ReturnOrderCreateNestedManyWithoutCustomerInput
}

export type CustomerUncheckedCreateInput = {
  id?: string
  userId: string
  name: string
  lastname: string
  document: string
  phone: string
  whatsapp?: string | null
  email: string
  city?: string | null
  department?: string | null
  address?: string | null
  notes?: string | null
  totalPurchases?: number
  balance?: number
  isBlocked?: boolean
  blockedReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutCustomerInput
  receivablePayments?: Prisma.ReceivablePaymentUncheckedCreateNestedManyWithoutCustomerInput
  returns?: Prisma.ReturnOrderUncheckedCreateNestedManyWithoutCustomerInput
}

export type CustomerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  lastname?: Prisma.StringFieldUpdateOperationsInput | string
  document?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalPurchases?: Prisma.IntFieldUpdateOperationsInput | number
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  isBlocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blockedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutCustomerProfileNestedInput
  orders?: Prisma.OrderUpdateManyWithoutCustomerNestedInput
  receivablePayments?: Prisma.ReceivablePaymentUpdateManyWithoutCustomerNestedInput
  returns?: Prisma.ReturnOrderUpdateManyWithoutCustomerNestedInput
}

export type CustomerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  lastname?: Prisma.StringFieldUpdateOperationsInput | string
  document?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalPurchases?: Prisma.IntFieldUpdateOperationsInput | number
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  isBlocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blockedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orders?: Prisma.OrderUncheckedUpdateManyWithoutCustomerNestedInput
  receivablePayments?: Prisma.ReceivablePaymentUncheckedUpdateManyWithoutCustomerNestedInput
  returns?: Prisma.ReturnOrderUncheckedUpdateManyWithoutCustomerNestedInput
}

export type CustomerCreateManyInput = {
  id?: string
  userId: string
  name: string
  lastname: string
  document: string
  phone: string
  whatsapp?: string | null
  email: string
  city?: string | null
  department?: string | null
  address?: string | null
  notes?: string | null
  totalPurchases?: number
  balance?: number
  isBlocked?: boolean
  blockedReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CustomerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  lastname?: Prisma.StringFieldUpdateOperationsInput | string
  document?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalPurchases?: Prisma.IntFieldUpdateOperationsInput | number
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  isBlocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blockedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  lastname?: Prisma.StringFieldUpdateOperationsInput | string
  document?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalPurchases?: Prisma.IntFieldUpdateOperationsInput | number
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  isBlocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blockedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerNullableScalarRelationFilter = {
  is?: Prisma.CustomerWhereInput | null
  isNot?: Prisma.CustomerWhereInput | null
}

export type CustomerOrderByRelevanceInput = {
  fields: Prisma.CustomerOrderByRelevanceFieldEnum | Prisma.CustomerOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type CustomerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  lastname?: Prisma.SortOrder
  document?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  whatsapp?: Prisma.SortOrder
  email?: Prisma.SortOrder
  city?: Prisma.SortOrder
  department?: Prisma.SortOrder
  address?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  totalPurchases?: Prisma.SortOrder
  balance?: Prisma.SortOrder
  isBlocked?: Prisma.SortOrder
  blockedReason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CustomerAvgOrderByAggregateInput = {
  totalPurchases?: Prisma.SortOrder
  balance?: Prisma.SortOrder
}

export type CustomerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  lastname?: Prisma.SortOrder
  document?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  whatsapp?: Prisma.SortOrder
  email?: Prisma.SortOrder
  city?: Prisma.SortOrder
  department?: Prisma.SortOrder
  address?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  totalPurchases?: Prisma.SortOrder
  balance?: Prisma.SortOrder
  isBlocked?: Prisma.SortOrder
  blockedReason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CustomerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  lastname?: Prisma.SortOrder
  document?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  whatsapp?: Prisma.SortOrder
  email?: Prisma.SortOrder
  city?: Prisma.SortOrder
  department?: Prisma.SortOrder
  address?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  totalPurchases?: Prisma.SortOrder
  balance?: Prisma.SortOrder
  isBlocked?: Prisma.SortOrder
  blockedReason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CustomerSumOrderByAggregateInput = {
  totalPurchases?: Prisma.SortOrder
  balance?: Prisma.SortOrder
}

export type CustomerScalarRelationFilter = {
  is?: Prisma.CustomerWhereInput
  isNot?: Prisma.CustomerWhereInput
}

export type CustomerCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CustomerCreateWithoutUserInput, Prisma.CustomerUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.CustomerCreateOrConnectWithoutUserInput
  connect?: Prisma.CustomerWhereUniqueInput
}

export type CustomerUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CustomerCreateWithoutUserInput, Prisma.CustomerUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.CustomerCreateOrConnectWithoutUserInput
  connect?: Prisma.CustomerWhereUniqueInput
}

export type CustomerUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CustomerCreateWithoutUserInput, Prisma.CustomerUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.CustomerCreateOrConnectWithoutUserInput
  upsert?: Prisma.CustomerUpsertWithoutUserInput
  disconnect?: Prisma.CustomerWhereInput | boolean
  delete?: Prisma.CustomerWhereInput | boolean
  connect?: Prisma.CustomerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CustomerUpdateToOneWithWhereWithoutUserInput, Prisma.CustomerUpdateWithoutUserInput>, Prisma.CustomerUncheckedUpdateWithoutUserInput>
}

export type CustomerUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CustomerCreateWithoutUserInput, Prisma.CustomerUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.CustomerCreateOrConnectWithoutUserInput
  upsert?: Prisma.CustomerUpsertWithoutUserInput
  disconnect?: Prisma.CustomerWhereInput | boolean
  delete?: Prisma.CustomerWhereInput | boolean
  connect?: Prisma.CustomerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CustomerUpdateToOneWithWhereWithoutUserInput, Prisma.CustomerUpdateWithoutUserInput>, Prisma.CustomerUncheckedUpdateWithoutUserInput>
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type CustomerCreateNestedOneWithoutReceivablePaymentsInput = {
  create?: Prisma.XOR<Prisma.CustomerCreateWithoutReceivablePaymentsInput, Prisma.CustomerUncheckedCreateWithoutReceivablePaymentsInput>
  connectOrCreate?: Prisma.CustomerCreateOrConnectWithoutReceivablePaymentsInput
  connect?: Prisma.CustomerWhereUniqueInput
}

export type CustomerUpdateOneRequiredWithoutReceivablePaymentsNestedInput = {
  create?: Prisma.XOR<Prisma.CustomerCreateWithoutReceivablePaymentsInput, Prisma.CustomerUncheckedCreateWithoutReceivablePaymentsInput>
  connectOrCreate?: Prisma.CustomerCreateOrConnectWithoutReceivablePaymentsInput
  upsert?: Prisma.CustomerUpsertWithoutReceivablePaymentsInput
  connect?: Prisma.CustomerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CustomerUpdateToOneWithWhereWithoutReceivablePaymentsInput, Prisma.CustomerUpdateWithoutReceivablePaymentsInput>, Prisma.CustomerUncheckedUpdateWithoutReceivablePaymentsInput>
}

export type CustomerCreateNestedOneWithoutOrdersInput = {
  create?: Prisma.XOR<Prisma.CustomerCreateWithoutOrdersInput, Prisma.CustomerUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.CustomerCreateOrConnectWithoutOrdersInput
  connect?: Prisma.CustomerWhereUniqueInput
}

export type CustomerUpdateOneWithoutOrdersNestedInput = {
  create?: Prisma.XOR<Prisma.CustomerCreateWithoutOrdersInput, Prisma.CustomerUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.CustomerCreateOrConnectWithoutOrdersInput
  upsert?: Prisma.CustomerUpsertWithoutOrdersInput
  disconnect?: Prisma.CustomerWhereInput | boolean
  delete?: Prisma.CustomerWhereInput | boolean
  connect?: Prisma.CustomerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CustomerUpdateToOneWithWhereWithoutOrdersInput, Prisma.CustomerUpdateWithoutOrdersInput>, Prisma.CustomerUncheckedUpdateWithoutOrdersInput>
}

export type CustomerCreateNestedOneWithoutReturnsInput = {
  create?: Prisma.XOR<Prisma.CustomerCreateWithoutReturnsInput, Prisma.CustomerUncheckedCreateWithoutReturnsInput>
  connectOrCreate?: Prisma.CustomerCreateOrConnectWithoutReturnsInput
  connect?: Prisma.CustomerWhereUniqueInput
}

export type CustomerUpdateOneWithoutReturnsNestedInput = {
  create?: Prisma.XOR<Prisma.CustomerCreateWithoutReturnsInput, Prisma.CustomerUncheckedCreateWithoutReturnsInput>
  connectOrCreate?: Prisma.CustomerCreateOrConnectWithoutReturnsInput
  upsert?: Prisma.CustomerUpsertWithoutReturnsInput
  disconnect?: Prisma.CustomerWhereInput | boolean
  delete?: Prisma.CustomerWhereInput | boolean
  connect?: Prisma.CustomerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CustomerUpdateToOneWithWhereWithoutReturnsInput, Prisma.CustomerUpdateWithoutReturnsInput>, Prisma.CustomerUncheckedUpdateWithoutReturnsInput>
}

export type CustomerCreateWithoutUserInput = {
  id?: string
  name: string
  lastname: string
  document: string
  phone: string
  whatsapp?: string | null
  email: string
  city?: string | null
  department?: string | null
  address?: string | null
  notes?: string | null
  totalPurchases?: number
  balance?: number
  isBlocked?: boolean
  blockedReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  orders?: Prisma.OrderCreateNestedManyWithoutCustomerInput
  receivablePayments?: Prisma.ReceivablePaymentCreateNestedManyWithoutCustomerInput
  returns?: Prisma.ReturnOrderCreateNestedManyWithoutCustomerInput
}

export type CustomerUncheckedCreateWithoutUserInput = {
  id?: string
  name: string
  lastname: string
  document: string
  phone: string
  whatsapp?: string | null
  email: string
  city?: string | null
  department?: string | null
  address?: string | null
  notes?: string | null
  totalPurchases?: number
  balance?: number
  isBlocked?: boolean
  blockedReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutCustomerInput
  receivablePayments?: Prisma.ReceivablePaymentUncheckedCreateNestedManyWithoutCustomerInput
  returns?: Prisma.ReturnOrderUncheckedCreateNestedManyWithoutCustomerInput
}

export type CustomerCreateOrConnectWithoutUserInput = {
  where: Prisma.CustomerWhereUniqueInput
  create: Prisma.XOR<Prisma.CustomerCreateWithoutUserInput, Prisma.CustomerUncheckedCreateWithoutUserInput>
}

export type CustomerUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.CustomerUpdateWithoutUserInput, Prisma.CustomerUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.CustomerCreateWithoutUserInput, Prisma.CustomerUncheckedCreateWithoutUserInput>
  where?: Prisma.CustomerWhereInput
}

export type CustomerUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.CustomerWhereInput
  data: Prisma.XOR<Prisma.CustomerUpdateWithoutUserInput, Prisma.CustomerUncheckedUpdateWithoutUserInput>
}

export type CustomerUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  lastname?: Prisma.StringFieldUpdateOperationsInput | string
  document?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalPurchases?: Prisma.IntFieldUpdateOperationsInput | number
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  isBlocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blockedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orders?: Prisma.OrderUpdateManyWithoutCustomerNestedInput
  receivablePayments?: Prisma.ReceivablePaymentUpdateManyWithoutCustomerNestedInput
  returns?: Prisma.ReturnOrderUpdateManyWithoutCustomerNestedInput
}

export type CustomerUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  lastname?: Prisma.StringFieldUpdateOperationsInput | string
  document?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalPurchases?: Prisma.IntFieldUpdateOperationsInput | number
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  isBlocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blockedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orders?: Prisma.OrderUncheckedUpdateManyWithoutCustomerNestedInput
  receivablePayments?: Prisma.ReceivablePaymentUncheckedUpdateManyWithoutCustomerNestedInput
  returns?: Prisma.ReturnOrderUncheckedUpdateManyWithoutCustomerNestedInput
}

export type CustomerCreateWithoutReceivablePaymentsInput = {
  id?: string
  name: string
  lastname: string
  document: string
  phone: string
  whatsapp?: string | null
  email: string
  city?: string | null
  department?: string | null
  address?: string | null
  notes?: string | null
  totalPurchases?: number
  balance?: number
  isBlocked?: boolean
  blockedReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutCustomerProfileInput
  orders?: Prisma.OrderCreateNestedManyWithoutCustomerInput
  returns?: Prisma.ReturnOrderCreateNestedManyWithoutCustomerInput
}

export type CustomerUncheckedCreateWithoutReceivablePaymentsInput = {
  id?: string
  userId: string
  name: string
  lastname: string
  document: string
  phone: string
  whatsapp?: string | null
  email: string
  city?: string | null
  department?: string | null
  address?: string | null
  notes?: string | null
  totalPurchases?: number
  balance?: number
  isBlocked?: boolean
  blockedReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutCustomerInput
  returns?: Prisma.ReturnOrderUncheckedCreateNestedManyWithoutCustomerInput
}

export type CustomerCreateOrConnectWithoutReceivablePaymentsInput = {
  where: Prisma.CustomerWhereUniqueInput
  create: Prisma.XOR<Prisma.CustomerCreateWithoutReceivablePaymentsInput, Prisma.CustomerUncheckedCreateWithoutReceivablePaymentsInput>
}

export type CustomerUpsertWithoutReceivablePaymentsInput = {
  update: Prisma.XOR<Prisma.CustomerUpdateWithoutReceivablePaymentsInput, Prisma.CustomerUncheckedUpdateWithoutReceivablePaymentsInput>
  create: Prisma.XOR<Prisma.CustomerCreateWithoutReceivablePaymentsInput, Prisma.CustomerUncheckedCreateWithoutReceivablePaymentsInput>
  where?: Prisma.CustomerWhereInput
}

export type CustomerUpdateToOneWithWhereWithoutReceivablePaymentsInput = {
  where?: Prisma.CustomerWhereInput
  data: Prisma.XOR<Prisma.CustomerUpdateWithoutReceivablePaymentsInput, Prisma.CustomerUncheckedUpdateWithoutReceivablePaymentsInput>
}

export type CustomerUpdateWithoutReceivablePaymentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  lastname?: Prisma.StringFieldUpdateOperationsInput | string
  document?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalPurchases?: Prisma.IntFieldUpdateOperationsInput | number
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  isBlocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blockedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutCustomerProfileNestedInput
  orders?: Prisma.OrderUpdateManyWithoutCustomerNestedInput
  returns?: Prisma.ReturnOrderUpdateManyWithoutCustomerNestedInput
}

export type CustomerUncheckedUpdateWithoutReceivablePaymentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  lastname?: Prisma.StringFieldUpdateOperationsInput | string
  document?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalPurchases?: Prisma.IntFieldUpdateOperationsInput | number
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  isBlocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blockedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orders?: Prisma.OrderUncheckedUpdateManyWithoutCustomerNestedInput
  returns?: Prisma.ReturnOrderUncheckedUpdateManyWithoutCustomerNestedInput
}

export type CustomerCreateWithoutOrdersInput = {
  id?: string
  name: string
  lastname: string
  document: string
  phone: string
  whatsapp?: string | null
  email: string
  city?: string | null
  department?: string | null
  address?: string | null
  notes?: string | null
  totalPurchases?: number
  balance?: number
  isBlocked?: boolean
  blockedReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutCustomerProfileInput
  receivablePayments?: Prisma.ReceivablePaymentCreateNestedManyWithoutCustomerInput
  returns?: Prisma.ReturnOrderCreateNestedManyWithoutCustomerInput
}

export type CustomerUncheckedCreateWithoutOrdersInput = {
  id?: string
  userId: string
  name: string
  lastname: string
  document: string
  phone: string
  whatsapp?: string | null
  email: string
  city?: string | null
  department?: string | null
  address?: string | null
  notes?: string | null
  totalPurchases?: number
  balance?: number
  isBlocked?: boolean
  blockedReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  receivablePayments?: Prisma.ReceivablePaymentUncheckedCreateNestedManyWithoutCustomerInput
  returns?: Prisma.ReturnOrderUncheckedCreateNestedManyWithoutCustomerInput
}

export type CustomerCreateOrConnectWithoutOrdersInput = {
  where: Prisma.CustomerWhereUniqueInput
  create: Prisma.XOR<Prisma.CustomerCreateWithoutOrdersInput, Prisma.CustomerUncheckedCreateWithoutOrdersInput>
}

export type CustomerUpsertWithoutOrdersInput = {
  update: Prisma.XOR<Prisma.CustomerUpdateWithoutOrdersInput, Prisma.CustomerUncheckedUpdateWithoutOrdersInput>
  create: Prisma.XOR<Prisma.CustomerCreateWithoutOrdersInput, Prisma.CustomerUncheckedCreateWithoutOrdersInput>
  where?: Prisma.CustomerWhereInput
}

export type CustomerUpdateToOneWithWhereWithoutOrdersInput = {
  where?: Prisma.CustomerWhereInput
  data: Prisma.XOR<Prisma.CustomerUpdateWithoutOrdersInput, Prisma.CustomerUncheckedUpdateWithoutOrdersInput>
}

export type CustomerUpdateWithoutOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  lastname?: Prisma.StringFieldUpdateOperationsInput | string
  document?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalPurchases?: Prisma.IntFieldUpdateOperationsInput | number
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  isBlocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blockedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutCustomerProfileNestedInput
  receivablePayments?: Prisma.ReceivablePaymentUpdateManyWithoutCustomerNestedInput
  returns?: Prisma.ReturnOrderUpdateManyWithoutCustomerNestedInput
}

export type CustomerUncheckedUpdateWithoutOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  lastname?: Prisma.StringFieldUpdateOperationsInput | string
  document?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalPurchases?: Prisma.IntFieldUpdateOperationsInput | number
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  isBlocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blockedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  receivablePayments?: Prisma.ReceivablePaymentUncheckedUpdateManyWithoutCustomerNestedInput
  returns?: Prisma.ReturnOrderUncheckedUpdateManyWithoutCustomerNestedInput
}

export type CustomerCreateWithoutReturnsInput = {
  id?: string
  name: string
  lastname: string
  document: string
  phone: string
  whatsapp?: string | null
  email: string
  city?: string | null
  department?: string | null
  address?: string | null
  notes?: string | null
  totalPurchases?: number
  balance?: number
  isBlocked?: boolean
  blockedReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutCustomerProfileInput
  orders?: Prisma.OrderCreateNestedManyWithoutCustomerInput
  receivablePayments?: Prisma.ReceivablePaymentCreateNestedManyWithoutCustomerInput
}

export type CustomerUncheckedCreateWithoutReturnsInput = {
  id?: string
  userId: string
  name: string
  lastname: string
  document: string
  phone: string
  whatsapp?: string | null
  email: string
  city?: string | null
  department?: string | null
  address?: string | null
  notes?: string | null
  totalPurchases?: number
  balance?: number
  isBlocked?: boolean
  blockedReason?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutCustomerInput
  receivablePayments?: Prisma.ReceivablePaymentUncheckedCreateNestedManyWithoutCustomerInput
}

export type CustomerCreateOrConnectWithoutReturnsInput = {
  where: Prisma.CustomerWhereUniqueInput
  create: Prisma.XOR<Prisma.CustomerCreateWithoutReturnsInput, Prisma.CustomerUncheckedCreateWithoutReturnsInput>
}

export type CustomerUpsertWithoutReturnsInput = {
  update: Prisma.XOR<Prisma.CustomerUpdateWithoutReturnsInput, Prisma.CustomerUncheckedUpdateWithoutReturnsInput>
  create: Prisma.XOR<Prisma.CustomerCreateWithoutReturnsInput, Prisma.CustomerUncheckedCreateWithoutReturnsInput>
  where?: Prisma.CustomerWhereInput
}

export type CustomerUpdateToOneWithWhereWithoutReturnsInput = {
  where?: Prisma.CustomerWhereInput
  data: Prisma.XOR<Prisma.CustomerUpdateWithoutReturnsInput, Prisma.CustomerUncheckedUpdateWithoutReturnsInput>
}

export type CustomerUpdateWithoutReturnsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  lastname?: Prisma.StringFieldUpdateOperationsInput | string
  document?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalPurchases?: Prisma.IntFieldUpdateOperationsInput | number
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  isBlocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blockedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutCustomerProfileNestedInput
  orders?: Prisma.OrderUpdateManyWithoutCustomerNestedInput
  receivablePayments?: Prisma.ReceivablePaymentUpdateManyWithoutCustomerNestedInput
}

export type CustomerUncheckedUpdateWithoutReturnsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  lastname?: Prisma.StringFieldUpdateOperationsInput | string
  document?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  department?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalPurchases?: Prisma.IntFieldUpdateOperationsInput | number
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  isBlocked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  blockedReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orders?: Prisma.OrderUncheckedUpdateManyWithoutCustomerNestedInput
  receivablePayments?: Prisma.ReceivablePaymentUncheckedUpdateManyWithoutCustomerNestedInput
}


/**
 * Count Type CustomerCountOutputType
 */

export type CustomerCountOutputType = {
  orders: number
  receivablePayments: number
  returns: number
}

export type CustomerCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  orders?: boolean | CustomerCountOutputTypeCountOrdersArgs
  receivablePayments?: boolean | CustomerCountOutputTypeCountReceivablePaymentsArgs
  returns?: boolean | CustomerCountOutputTypeCountReturnsArgs
}

/**
 * CustomerCountOutputType without action
 */
export type CustomerCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerCountOutputType
   */
  select?: Prisma.CustomerCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CustomerCountOutputType without action
 */
export type CustomerCountOutputTypeCountOrdersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderWhereInput
}

/**
 * CustomerCountOutputType without action
 */
export type CustomerCountOutputTypeCountReceivablePaymentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReceivablePaymentWhereInput
}

/**
 * CustomerCountOutputType without action
 */
export type CustomerCountOutputTypeCountReturnsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReturnOrderWhereInput
}


export type CustomerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  name?: boolean
  lastname?: boolean
  document?: boolean
  phone?: boolean
  whatsapp?: boolean
  email?: boolean
  city?: boolean
  department?: boolean
  address?: boolean
  notes?: boolean
  totalPurchases?: boolean
  balance?: boolean
  isBlocked?: boolean
  blockedReason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  orders?: boolean | Prisma.Customer$ordersArgs<ExtArgs>
  receivablePayments?: boolean | Prisma.Customer$receivablePaymentsArgs<ExtArgs>
  returns?: boolean | Prisma.Customer$returnsArgs<ExtArgs>
  _count?: boolean | Prisma.CustomerCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customer"]>



export type CustomerSelectScalar = {
  id?: boolean
  userId?: boolean
  name?: boolean
  lastname?: boolean
  document?: boolean
  phone?: boolean
  whatsapp?: boolean
  email?: boolean
  city?: boolean
  department?: boolean
  address?: boolean
  notes?: boolean
  totalPurchases?: boolean
  balance?: boolean
  isBlocked?: boolean
  blockedReason?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CustomerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "name" | "lastname" | "document" | "phone" | "whatsapp" | "email" | "city" | "department" | "address" | "notes" | "totalPurchases" | "balance" | "isBlocked" | "blockedReason" | "createdAt" | "updatedAt", ExtArgs["result"]["customer"]>
export type CustomerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  orders?: boolean | Prisma.Customer$ordersArgs<ExtArgs>
  receivablePayments?: boolean | Prisma.Customer$receivablePaymentsArgs<ExtArgs>
  returns?: boolean | Prisma.Customer$returnsArgs<ExtArgs>
  _count?: boolean | Prisma.CustomerCountOutputTypeDefaultArgs<ExtArgs>
}

export type $CustomerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Customer"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    orders: Prisma.$OrderPayload<ExtArgs>[]
    receivablePayments: Prisma.$ReceivablePaymentPayload<ExtArgs>[]
    returns: Prisma.$ReturnOrderPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    name: string
    lastname: string
    document: string
    phone: string
    whatsapp: string | null
    email: string
    city: string | null
    department: string | null
    address: string | null
    notes: string | null
    totalPurchases: number
    balance: number
    isBlocked: boolean
    blockedReason: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["customer"]>
  composites: {}
}

export type CustomerGetPayload<S extends boolean | null | undefined | CustomerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CustomerPayload, S>

export type CustomerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CustomerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CustomerCountAggregateInputType | true
  }

export interface CustomerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Customer'], meta: { name: 'Customer' } }
  /**
   * Find zero or one Customer that matches the filter.
   * @param {CustomerFindUniqueArgs} args - Arguments to find a Customer
   * @example
   * // Get one Customer
   * const customer = await prisma.customer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CustomerFindUniqueArgs>(args: Prisma.SelectSubset<T, CustomerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Customer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CustomerFindUniqueOrThrowArgs} args - Arguments to find a Customer
   * @example
   * // Get one Customer
   * const customer = await prisma.customer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CustomerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CustomerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Customer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerFindFirstArgs} args - Arguments to find a Customer
   * @example
   * // Get one Customer
   * const customer = await prisma.customer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CustomerFindFirstArgs>(args?: Prisma.SelectSubset<T, CustomerFindFirstArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Customer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerFindFirstOrThrowArgs} args - Arguments to find a Customer
   * @example
   * // Get one Customer
   * const customer = await prisma.customer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CustomerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CustomerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Customers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Customers
   * const customers = await prisma.customer.findMany()
   * 
   * // Get first 10 Customers
   * const customers = await prisma.customer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const customerWithIdOnly = await prisma.customer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CustomerFindManyArgs>(args?: Prisma.SelectSubset<T, CustomerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Customer.
   * @param {CustomerCreateArgs} args - Arguments to create a Customer.
   * @example
   * // Create one Customer
   * const Customer = await prisma.customer.create({
   *   data: {
   *     // ... data to create a Customer
   *   }
   * })
   * 
   */
  create<T extends CustomerCreateArgs>(args: Prisma.SelectSubset<T, CustomerCreateArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Customers.
   * @param {CustomerCreateManyArgs} args - Arguments to create many Customers.
   * @example
   * // Create many Customers
   * const customer = await prisma.customer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CustomerCreateManyArgs>(args?: Prisma.SelectSubset<T, CustomerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Customer.
   * @param {CustomerDeleteArgs} args - Arguments to delete one Customer.
   * @example
   * // Delete one Customer
   * const Customer = await prisma.customer.delete({
   *   where: {
   *     // ... filter to delete one Customer
   *   }
   * })
   * 
   */
  delete<T extends CustomerDeleteArgs>(args: Prisma.SelectSubset<T, CustomerDeleteArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Customer.
   * @param {CustomerUpdateArgs} args - Arguments to update one Customer.
   * @example
   * // Update one Customer
   * const customer = await prisma.customer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CustomerUpdateArgs>(args: Prisma.SelectSubset<T, CustomerUpdateArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Customers.
   * @param {CustomerDeleteManyArgs} args - Arguments to filter Customers to delete.
   * @example
   * // Delete a few Customers
   * const { count } = await prisma.customer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CustomerDeleteManyArgs>(args?: Prisma.SelectSubset<T, CustomerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Customers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Customers
   * const customer = await prisma.customer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CustomerUpdateManyArgs>(args: Prisma.SelectSubset<T, CustomerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Customer.
   * @param {CustomerUpsertArgs} args - Arguments to update or create a Customer.
   * @example
   * // Update or create a Customer
   * const customer = await prisma.customer.upsert({
   *   create: {
   *     // ... data to create a Customer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Customer we want to update
   *   }
   * })
   */
  upsert<T extends CustomerUpsertArgs>(args: Prisma.SelectSubset<T, CustomerUpsertArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Customers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerCountArgs} args - Arguments to filter Customers to count.
   * @example
   * // Count the number of Customers
   * const count = await prisma.customer.count({
   *   where: {
   *     // ... the filter for the Customers we want to count
   *   }
   * })
  **/
  count<T extends CustomerCountArgs>(
    args?: Prisma.Subset<T, CustomerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CustomerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Customer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CustomerAggregateArgs>(args: Prisma.Subset<T, CustomerAggregateArgs>): Prisma.PrismaPromise<GetCustomerAggregateType<T>>

  /**
   * Group by Customer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CustomerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CustomerGroupByArgs['orderBy'] }
      : { orderBy?: CustomerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CustomerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCustomerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Customer model
 */
readonly fields: CustomerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Customer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CustomerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  orders<T extends Prisma.Customer$ordersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Customer$ordersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  receivablePayments<T extends Prisma.Customer$receivablePaymentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Customer$receivablePaymentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReceivablePaymentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  returns<T extends Prisma.Customer$returnsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Customer$returnsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReturnOrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Customer model
 */
export interface CustomerFieldRefs {
  readonly id: Prisma.FieldRef<"Customer", 'String'>
  readonly userId: Prisma.FieldRef<"Customer", 'String'>
  readonly name: Prisma.FieldRef<"Customer", 'String'>
  readonly lastname: Prisma.FieldRef<"Customer", 'String'>
  readonly document: Prisma.FieldRef<"Customer", 'String'>
  readonly phone: Prisma.FieldRef<"Customer", 'String'>
  readonly whatsapp: Prisma.FieldRef<"Customer", 'String'>
  readonly email: Prisma.FieldRef<"Customer", 'String'>
  readonly city: Prisma.FieldRef<"Customer", 'String'>
  readonly department: Prisma.FieldRef<"Customer", 'String'>
  readonly address: Prisma.FieldRef<"Customer", 'String'>
  readonly notes: Prisma.FieldRef<"Customer", 'String'>
  readonly totalPurchases: Prisma.FieldRef<"Customer", 'Int'>
  readonly balance: Prisma.FieldRef<"Customer", 'Float'>
  readonly isBlocked: Prisma.FieldRef<"Customer", 'Boolean'>
  readonly blockedReason: Prisma.FieldRef<"Customer", 'String'>
  readonly createdAt: Prisma.FieldRef<"Customer", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Customer", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Customer findUnique
 */
export type CustomerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  /**
   * Filter, which Customer to fetch.
   */
  where: Prisma.CustomerWhereUniqueInput
}

/**
 * Customer findUniqueOrThrow
 */
export type CustomerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  /**
   * Filter, which Customer to fetch.
   */
  where: Prisma.CustomerWhereUniqueInput
}

/**
 * Customer findFirst
 */
export type CustomerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  /**
   * Filter, which Customer to fetch.
   */
  where?: Prisma.CustomerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Customers to fetch.
   */
  orderBy?: Prisma.CustomerOrderByWithRelationInput | Prisma.CustomerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Customers.
   */
  cursor?: Prisma.CustomerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Customers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Customers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Customers.
   */
  distinct?: Prisma.CustomerScalarFieldEnum | Prisma.CustomerScalarFieldEnum[]
}

/**
 * Customer findFirstOrThrow
 */
export type CustomerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  /**
   * Filter, which Customer to fetch.
   */
  where?: Prisma.CustomerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Customers to fetch.
   */
  orderBy?: Prisma.CustomerOrderByWithRelationInput | Prisma.CustomerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Customers.
   */
  cursor?: Prisma.CustomerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Customers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Customers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Customers.
   */
  distinct?: Prisma.CustomerScalarFieldEnum | Prisma.CustomerScalarFieldEnum[]
}

/**
 * Customer findMany
 */
export type CustomerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  /**
   * Filter, which Customers to fetch.
   */
  where?: Prisma.CustomerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Customers to fetch.
   */
  orderBy?: Prisma.CustomerOrderByWithRelationInput | Prisma.CustomerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Customers.
   */
  cursor?: Prisma.CustomerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Customers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Customers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Customers.
   */
  distinct?: Prisma.CustomerScalarFieldEnum | Prisma.CustomerScalarFieldEnum[]
}

/**
 * Customer create
 */
export type CustomerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  /**
   * The data needed to create a Customer.
   */
  data: Prisma.XOR<Prisma.CustomerCreateInput, Prisma.CustomerUncheckedCreateInput>
}

/**
 * Customer createMany
 */
export type CustomerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Customers.
   */
  data: Prisma.CustomerCreateManyInput | Prisma.CustomerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Customer update
 */
export type CustomerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  /**
   * The data needed to update a Customer.
   */
  data: Prisma.XOR<Prisma.CustomerUpdateInput, Prisma.CustomerUncheckedUpdateInput>
  /**
   * Choose, which Customer to update.
   */
  where: Prisma.CustomerWhereUniqueInput
}

/**
 * Customer updateMany
 */
export type CustomerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Customers.
   */
  data: Prisma.XOR<Prisma.CustomerUpdateManyMutationInput, Prisma.CustomerUncheckedUpdateManyInput>
  /**
   * Filter which Customers to update
   */
  where?: Prisma.CustomerWhereInput
  /**
   * Limit how many Customers to update.
   */
  limit?: number
}

/**
 * Customer upsert
 */
export type CustomerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  /**
   * The filter to search for the Customer to update in case it exists.
   */
  where: Prisma.CustomerWhereUniqueInput
  /**
   * In case the Customer found by the `where` argument doesn't exist, create a new Customer with this data.
   */
  create: Prisma.XOR<Prisma.CustomerCreateInput, Prisma.CustomerUncheckedCreateInput>
  /**
   * In case the Customer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CustomerUpdateInput, Prisma.CustomerUncheckedUpdateInput>
}

/**
 * Customer delete
 */
export type CustomerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  /**
   * Filter which Customer to delete.
   */
  where: Prisma.CustomerWhereUniqueInput
}

/**
 * Customer deleteMany
 */
export type CustomerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Customers to delete
   */
  where?: Prisma.CustomerWhereInput
  /**
   * Limit how many Customers to delete.
   */
  limit?: number
}

/**
 * Customer.orders
 */
export type Customer$ordersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  where?: Prisma.OrderWhereInput
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  cursor?: Prisma.OrderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderScalarFieldEnum | Prisma.OrderScalarFieldEnum[]
}

/**
 * Customer.receivablePayments
 */
export type Customer$receivablePaymentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReceivablePayment
   */
  select?: Prisma.ReceivablePaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReceivablePayment
   */
  omit?: Prisma.ReceivablePaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReceivablePaymentInclude<ExtArgs> | null
  where?: Prisma.ReceivablePaymentWhereInput
  orderBy?: Prisma.ReceivablePaymentOrderByWithRelationInput | Prisma.ReceivablePaymentOrderByWithRelationInput[]
  cursor?: Prisma.ReceivablePaymentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReceivablePaymentScalarFieldEnum | Prisma.ReceivablePaymentScalarFieldEnum[]
}

/**
 * Customer.returns
 */
export type Customer$returnsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReturnOrder
   */
  select?: Prisma.ReturnOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReturnOrder
   */
  omit?: Prisma.ReturnOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReturnOrderInclude<ExtArgs> | null
  where?: Prisma.ReturnOrderWhereInput
  orderBy?: Prisma.ReturnOrderOrderByWithRelationInput | Prisma.ReturnOrderOrderByWithRelationInput[]
  cursor?: Prisma.ReturnOrderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReturnOrderScalarFieldEnum | Prisma.ReturnOrderScalarFieldEnum[]
}

/**
 * Customer without action
 */
export type CustomerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
}
