
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Role: 'Role',
  Permission: 'Permission',
  Customer: 'Customer',
  ReceivablePayment: 'ReceivablePayment',
  Address: 'Address',
  Category: 'Category',
  Brand: 'Brand',
  Product: 'Product',
  ProductImage: 'ProductImage',
  ProductSpec: 'ProductSpec',
  ProductTag: 'ProductTag',
  CartItem: 'CartItem',
  WishlistItem: 'WishlistItem',
  Order: 'Order',
  OrderItem: 'OrderItem',
  OrderStatusHistory: 'OrderStatusHistory',
  Payment: 'Payment',
  Coupon: 'Coupon',
  AuditLog: 'AuditLog',
  Setting: 'Setting',
  PaymentMethod: 'PaymentMethod',
  Notification: 'Notification',
  Session: 'Session',
  Supplier: 'Supplier',
  Purchase: 'Purchase',
  PurchaseItem: 'PurchaseItem',
  StockMovement: 'StockMovement',
  ReturnOrder: 'ReturnOrder',
  ReturnItem: 'ReturnItem',
  CashSession: 'CashSession',
  CashMovement: 'CashMovement'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  lastname: 'lastname',
  document: 'document',
  phone: 'phone',
  whatsapp: 'whatsapp',
  email: 'email',
  passwordHash: 'passwordHash',
  city: 'city',
  department: 'department',
  address: 'address',
  roleId: 'roleId',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  createdAt: 'createdAt'
} as const

export type RoleScalarFieldEnum = (typeof RoleScalarFieldEnum)[keyof typeof RoleScalarFieldEnum]


export const PermissionScalarFieldEnum = {
  id: 'id',
  roleId: 'roleId',
  resource: 'resource',
  action: 'action',
  createdAt: 'createdAt'
} as const

export type PermissionScalarFieldEnum = (typeof PermissionScalarFieldEnum)[keyof typeof PermissionScalarFieldEnum]


export const CustomerScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  lastname: 'lastname',
  document: 'document',
  phone: 'phone',
  whatsapp: 'whatsapp',
  email: 'email',
  city: 'city',
  department: 'department',
  address: 'address',
  notes: 'notes',
  totalPurchases: 'totalPurchases',
  balance: 'balance',
  isBlocked: 'isBlocked',
  blockedReason: 'blockedReason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CustomerScalarFieldEnum = (typeof CustomerScalarFieldEnum)[keyof typeof CustomerScalarFieldEnum]


export const ReceivablePaymentScalarFieldEnum = {
  id: 'id',
  customerId: 'customerId',
  type: 'type',
  amount: 'amount',
  method: 'method',
  reference: 'reference',
  notes: 'notes',
  createdBy: 'createdBy',
  createdAt: 'createdAt'
} as const

export type ReceivablePaymentScalarFieldEnum = (typeof ReceivablePaymentScalarFieldEnum)[keyof typeof ReceivablePaymentScalarFieldEnum]


export const AddressScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  label: 'label',
  address: 'address',
  city: 'city',
  department: 'department',
  isDefault: 'isDefault',
  createdAt: 'createdAt'
} as const

export type AddressScalarFieldEnum = (typeof AddressScalarFieldEnum)[keyof typeof AddressScalarFieldEnum]


export const CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  parentId: 'parentId',
  description: 'description',
  image: 'image',
  isActive: 'isActive',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const BrandScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  logo: 'logo',
  description: 'description',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BrandScalarFieldEnum = (typeof BrandScalarFieldEnum)[keyof typeof BrandScalarFieldEnum]


export const ProductScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  brandId: 'brandId',
  categoryId: 'categoryId',
  description: 'description',
  shortDescription: 'shortDescription',
  sku: 'sku',
  manufacturerCode: 'manufacturerCode',
  price: 'price',
  comparePrice: 'comparePrice',
  costPrice: 'costPrice',
  currency: 'currency',
  stock: 'stock',
  minStock: 'minStock',
  unit: 'unit',
  unitCost: 'unitCost',
  salePrice: 'salePrice',
  wholesalePrice: 'wholesalePrice',
  barcode: 'barcode',
  secondaryBarcode: 'secondaryBarcode',
  lastPurchaseCost: 'lastPurchaseCost',
  brandName: 'brandName',
  weight: 'weight',
  isActive: 'isActive',
  isFeatured: 'isFeatured',
  isNew: 'isNew',
  metaTitle: 'metaTitle',
  metaDescription: 'metaDescription',
  rating: 'rating',
  reviews: 'reviews',
  sold: 'sold',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProductScalarFieldEnum = (typeof ProductScalarFieldEnum)[keyof typeof ProductScalarFieldEnum]


export const ProductImageScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  url: 'url',
  alt: 'alt',
  isPrimary: 'isPrimary',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt'
} as const

export type ProductImageScalarFieldEnum = (typeof ProductImageScalarFieldEnum)[keyof typeof ProductImageScalarFieldEnum]


export const ProductSpecScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  specName: 'specName',
  specValue: 'specValue',
  createdAt: 'createdAt'
} as const

export type ProductSpecScalarFieldEnum = (typeof ProductSpecScalarFieldEnum)[keyof typeof ProductSpecScalarFieldEnum]


export const ProductTagScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  tag: 'tag',
  createdAt: 'createdAt'
} as const

export type ProductTagScalarFieldEnum = (typeof ProductTagScalarFieldEnum)[keyof typeof ProductTagScalarFieldEnum]


export const CartItemScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  userId: 'userId',
  productId: 'productId',
  quantity: 'quantity',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CartItemScalarFieldEnum = (typeof CartItemScalarFieldEnum)[keyof typeof CartItemScalarFieldEnum]


export const WishlistItemScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  productId: 'productId',
  createdAt: 'createdAt'
} as const

export type WishlistItemScalarFieldEnum = (typeof WishlistItemScalarFieldEnum)[keyof typeof WishlistItemScalarFieldEnum]


export const OrderScalarFieldEnum = {
  id: 'id',
  orderNumber: 'orderNumber',
  userId: 'userId',
  customerId: 'customerId',
  sellerId: 'sellerId',
  status: 'status',
  subtotal: 'subtotal',
  discount: 'discount',
  shipping: 'shipping',
  total: 'total',
  paymentMethod: 'paymentMethod',
  paymentStatus: 'paymentStatus',
  couponId: 'couponId',
  notes: 'notes',
  customerName: 'customerName',
  customerPhone: 'customerPhone',
  customerEmail: 'customerEmail',
  customerAddress: 'customerAddress',
  customerCity: 'customerCity',
  deliveryMethod: 'deliveryMethod',
  amountPaid: 'amountPaid',
  paidAt: 'paidAt',
  deliveredAt: 'deliveredAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type OrderScalarFieldEnum = (typeof OrderScalarFieldEnum)[keyof typeof OrderScalarFieldEnum]


export const OrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  productName: 'productName',
  productSku: 'productSku',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  subtotal: 'subtotal',
  createdAt: 'createdAt'
} as const

export type OrderItemScalarFieldEnum = (typeof OrderItemScalarFieldEnum)[keyof typeof OrderItemScalarFieldEnum]


export const OrderStatusHistoryScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  status: 'status',
  changedBy: 'changedBy',
  notes: 'notes',
  createdAt: 'createdAt'
} as const

export type OrderStatusHistoryScalarFieldEnum = (typeof OrderStatusHistoryScalarFieldEnum)[keyof typeof OrderStatusHistoryScalarFieldEnum]


export const PaymentScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  gateway: 'gateway',
  transactionId: 'transactionId',
  amount: 'amount',
  currency: 'currency',
  status: 'status',
  payload: 'payload',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PaymentScalarFieldEnum = (typeof PaymentScalarFieldEnum)[keyof typeof PaymentScalarFieldEnum]


export const CouponScalarFieldEnum = {
  id: 'id',
  code: 'code',
  type: 'type',
  value: 'value',
  minPurchase: 'minPurchase',
  maxUses: 'maxUses',
  usedCount: 'usedCount',
  startsAt: 'startsAt',
  expiresAt: 'expiresAt',
  isActive: 'isActive',
  createdAt: 'createdAt'
} as const

export type CouponScalarFieldEnum = (typeof CouponScalarFieldEnum)[keyof typeof CouponScalarFieldEnum]


export const AuditLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  action: 'action',
  resource: 'resource',
  resourceId: 'resourceId',
  details: 'details',
  ipAddress: 'ipAddress',
  createdAt: 'createdAt'
} as const

export type AuditLogScalarFieldEnum = (typeof AuditLogScalarFieldEnum)[keyof typeof AuditLogScalarFieldEnum]


export const SettingScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SettingScalarFieldEnum = (typeof SettingScalarFieldEnum)[keyof typeof SettingScalarFieldEnum]


export const PaymentMethodScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  icon: 'icon',
  description: 'description',
  commission: 'commission',
  minAmount: 'minAmount',
  isActive: 'isActive',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PaymentMethodScalarFieldEnum = (typeof PaymentMethodScalarFieldEnum)[keyof typeof PaymentMethodScalarFieldEnum]


export const NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  title: 'title',
  message: 'message',
  isRead: 'isRead',
  link: 'link',
  createdAt: 'createdAt'
} as const

export type NotificationScalarFieldEnum = (typeof NotificationScalarFieldEnum)[keyof typeof NotificationScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  data: 'data',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const SupplierScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  ruc: 'ruc',
  email: 'email',
  phone: 'phone',
  whatsapp: 'whatsapp',
  address: 'address',
  city: 'city',
  notes: 'notes',
  paymentTerms: 'paymentTerms',
  contacts: 'contacts',
  balance: 'balance',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SupplierScalarFieldEnum = (typeof SupplierScalarFieldEnum)[keyof typeof SupplierScalarFieldEnum]


export const PurchaseScalarFieldEnum = {
  id: 'id',
  purchaseNumber: 'purchaseNumber',
  invoiceNumber: 'invoiceNumber',
  shippingCost: 'shippingCost',
  supplierId: 'supplierId',
  status: 'status',
  subtotal: 'subtotal',
  discount: 'discount',
  tax: 'tax',
  total: 'total',
  paymentStatus: 'paymentStatus',
  amountPaid: 'amountPaid',
  notes: 'notes',
  receivedAt: 'receivedAt',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PurchaseScalarFieldEnum = (typeof PurchaseScalarFieldEnum)[keyof typeof PurchaseScalarFieldEnum]


export const PurchaseItemScalarFieldEnum = {
  id: 'id',
  purchaseId: 'purchaseId',
  productId: 'productId',
  productName: 'productName',
  productSku: 'productSku',
  quantity: 'quantity',
  receivedQty: 'receivedQty',
  unitCost: 'unitCost',
  subtotal: 'subtotal',
  notes: 'notes',
  createdAt: 'createdAt'
} as const

export type PurchaseItemScalarFieldEnum = (typeof PurchaseItemScalarFieldEnum)[keyof typeof PurchaseItemScalarFieldEnum]


export const StockMovementScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  type: 'type',
  quantity: 'quantity',
  reason: 'reason',
  reference: 'reference',
  unit: 'unit',
  unitCost: 'unitCost',
  stockBefore: 'stockBefore',
  stockAfter: 'stockAfter',
  notes: 'notes',
  userId: 'userId',
  createdAt: 'createdAt'
} as const

export type StockMovementScalarFieldEnum = (typeof StockMovementScalarFieldEnum)[keyof typeof StockMovementScalarFieldEnum]


export const ReturnOrderScalarFieldEnum = {
  id: 'id',
  returnNumber: 'returnNumber',
  orderId: 'orderId',
  customerId: 'customerId',
  customerName: 'customerName',
  status: 'status',
  reason: 'reason',
  refundAmount: 'refundAmount',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ReturnOrderScalarFieldEnum = (typeof ReturnOrderScalarFieldEnum)[keyof typeof ReturnOrderScalarFieldEnum]


export const ReturnItemScalarFieldEnum = {
  id: 'id',
  returnId: 'returnId',
  productId: 'productId',
  productName: 'productName',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  condition: 'condition',
  createdAt: 'createdAt'
} as const

export type ReturnItemScalarFieldEnum = (typeof ReturnItemScalarFieldEnum)[keyof typeof ReturnItemScalarFieldEnum]


export const CashSessionScalarFieldEnum = {
  id: 'id',
  openedBy: 'openedBy',
  openedAt: 'openedAt',
  closedAt: 'closedAt',
  openingAmount: 'openingAmount',
  closingAmount: 'closingAmount',
  expectedAmount: 'expectedAmount',
  notes: 'notes',
  status: 'status',
  closedBy: 'closedBy'
} as const

export type CashSessionScalarFieldEnum = (typeof CashSessionScalarFieldEnum)[keyof typeof CashSessionScalarFieldEnum]


export const CashMovementScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  type: 'type',
  category: 'category',
  amount: 'amount',
  description: 'description',
  createdBy: 'createdBy',
  createdAt: 'createdAt'
} as const

export type CashMovementScalarFieldEnum = (typeof CashMovementScalarFieldEnum)[keyof typeof CashMovementScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const UserOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  lastname: 'lastname',
  document: 'document',
  phone: 'phone',
  whatsapp: 'whatsapp',
  email: 'email',
  passwordHash: 'passwordHash',
  city: 'city',
  department: 'department',
  address: 'address',
  roleId: 'roleId'
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]


export const RoleOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description'
} as const

export type RoleOrderByRelevanceFieldEnum = (typeof RoleOrderByRelevanceFieldEnum)[keyof typeof RoleOrderByRelevanceFieldEnum]


export const PermissionOrderByRelevanceFieldEnum = {
  id: 'id',
  roleId: 'roleId',
  resource: 'resource',
  action: 'action'
} as const

export type PermissionOrderByRelevanceFieldEnum = (typeof PermissionOrderByRelevanceFieldEnum)[keyof typeof PermissionOrderByRelevanceFieldEnum]


export const CustomerOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  lastname: 'lastname',
  document: 'document',
  phone: 'phone',
  whatsapp: 'whatsapp',
  email: 'email',
  city: 'city',
  department: 'department',
  address: 'address',
  notes: 'notes',
  blockedReason: 'blockedReason'
} as const

export type CustomerOrderByRelevanceFieldEnum = (typeof CustomerOrderByRelevanceFieldEnum)[keyof typeof CustomerOrderByRelevanceFieldEnum]


export const ReceivablePaymentOrderByRelevanceFieldEnum = {
  id: 'id',
  customerId: 'customerId',
  type: 'type',
  method: 'method',
  reference: 'reference',
  notes: 'notes',
  createdBy: 'createdBy'
} as const

export type ReceivablePaymentOrderByRelevanceFieldEnum = (typeof ReceivablePaymentOrderByRelevanceFieldEnum)[keyof typeof ReceivablePaymentOrderByRelevanceFieldEnum]


export const AddressOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  label: 'label',
  address: 'address',
  city: 'city',
  department: 'department'
} as const

export type AddressOrderByRelevanceFieldEnum = (typeof AddressOrderByRelevanceFieldEnum)[keyof typeof AddressOrderByRelevanceFieldEnum]


export const CategoryOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  parentId: 'parentId',
  description: 'description',
  image: 'image'
} as const

export type CategoryOrderByRelevanceFieldEnum = (typeof CategoryOrderByRelevanceFieldEnum)[keyof typeof CategoryOrderByRelevanceFieldEnum]


export const BrandOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  logo: 'logo',
  description: 'description'
} as const

export type BrandOrderByRelevanceFieldEnum = (typeof BrandOrderByRelevanceFieldEnum)[keyof typeof BrandOrderByRelevanceFieldEnum]


export const ProductOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  brandId: 'brandId',
  categoryId: 'categoryId',
  description: 'description',
  shortDescription: 'shortDescription',
  sku: 'sku',
  manufacturerCode: 'manufacturerCode',
  currency: 'currency',
  unit: 'unit',
  barcode: 'barcode',
  secondaryBarcode: 'secondaryBarcode',
  brandName: 'brandName',
  metaTitle: 'metaTitle',
  metaDescription: 'metaDescription'
} as const

export type ProductOrderByRelevanceFieldEnum = (typeof ProductOrderByRelevanceFieldEnum)[keyof typeof ProductOrderByRelevanceFieldEnum]


export const ProductImageOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  url: 'url',
  alt: 'alt'
} as const

export type ProductImageOrderByRelevanceFieldEnum = (typeof ProductImageOrderByRelevanceFieldEnum)[keyof typeof ProductImageOrderByRelevanceFieldEnum]


export const ProductSpecOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  specName: 'specName',
  specValue: 'specValue'
} as const

export type ProductSpecOrderByRelevanceFieldEnum = (typeof ProductSpecOrderByRelevanceFieldEnum)[keyof typeof ProductSpecOrderByRelevanceFieldEnum]


export const ProductTagOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  tag: 'tag'
} as const

export type ProductTagOrderByRelevanceFieldEnum = (typeof ProductTagOrderByRelevanceFieldEnum)[keyof typeof ProductTagOrderByRelevanceFieldEnum]


export const CartItemOrderByRelevanceFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  userId: 'userId',
  productId: 'productId'
} as const

export type CartItemOrderByRelevanceFieldEnum = (typeof CartItemOrderByRelevanceFieldEnum)[keyof typeof CartItemOrderByRelevanceFieldEnum]


export const WishlistItemOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  productId: 'productId'
} as const

export type WishlistItemOrderByRelevanceFieldEnum = (typeof WishlistItemOrderByRelevanceFieldEnum)[keyof typeof WishlistItemOrderByRelevanceFieldEnum]


export const OrderOrderByRelevanceFieldEnum = {
  id: 'id',
  orderNumber: 'orderNumber',
  userId: 'userId',
  customerId: 'customerId',
  sellerId: 'sellerId',
  status: 'status',
  paymentMethod: 'paymentMethod',
  paymentStatus: 'paymentStatus',
  couponId: 'couponId',
  notes: 'notes',
  customerName: 'customerName',
  customerPhone: 'customerPhone',
  customerEmail: 'customerEmail',
  customerAddress: 'customerAddress',
  customerCity: 'customerCity',
  deliveryMethod: 'deliveryMethod'
} as const

export type OrderOrderByRelevanceFieldEnum = (typeof OrderOrderByRelevanceFieldEnum)[keyof typeof OrderOrderByRelevanceFieldEnum]


export const OrderItemOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  productName: 'productName',
  productSku: 'productSku'
} as const

export type OrderItemOrderByRelevanceFieldEnum = (typeof OrderItemOrderByRelevanceFieldEnum)[keyof typeof OrderItemOrderByRelevanceFieldEnum]


export const OrderStatusHistoryOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  status: 'status',
  changedBy: 'changedBy',
  notes: 'notes'
} as const

export type OrderStatusHistoryOrderByRelevanceFieldEnum = (typeof OrderStatusHistoryOrderByRelevanceFieldEnum)[keyof typeof OrderStatusHistoryOrderByRelevanceFieldEnum]


export const PaymentOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  gateway: 'gateway',
  transactionId: 'transactionId',
  currency: 'currency',
  status: 'status',
  payload: 'payload'
} as const

export type PaymentOrderByRelevanceFieldEnum = (typeof PaymentOrderByRelevanceFieldEnum)[keyof typeof PaymentOrderByRelevanceFieldEnum]


export const CouponOrderByRelevanceFieldEnum = {
  id: 'id',
  code: 'code',
  type: 'type'
} as const

export type CouponOrderByRelevanceFieldEnum = (typeof CouponOrderByRelevanceFieldEnum)[keyof typeof CouponOrderByRelevanceFieldEnum]


export const AuditLogOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  action: 'action',
  resource: 'resource',
  resourceId: 'resourceId',
  details: 'details',
  ipAddress: 'ipAddress'
} as const

export type AuditLogOrderByRelevanceFieldEnum = (typeof AuditLogOrderByRelevanceFieldEnum)[keyof typeof AuditLogOrderByRelevanceFieldEnum]


export const SettingOrderByRelevanceFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value'
} as const

export type SettingOrderByRelevanceFieldEnum = (typeof SettingOrderByRelevanceFieldEnum)[keyof typeof SettingOrderByRelevanceFieldEnum]


export const PaymentMethodOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  icon: 'icon',
  description: 'description'
} as const

export type PaymentMethodOrderByRelevanceFieldEnum = (typeof PaymentMethodOrderByRelevanceFieldEnum)[keyof typeof PaymentMethodOrderByRelevanceFieldEnum]


export const NotificationOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  title: 'title',
  message: 'message',
  link: 'link'
} as const

export type NotificationOrderByRelevanceFieldEnum = (typeof NotificationOrderByRelevanceFieldEnum)[keyof typeof NotificationOrderByRelevanceFieldEnum]


export const SessionOrderByRelevanceFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  data: 'data'
} as const

export type SessionOrderByRelevanceFieldEnum = (typeof SessionOrderByRelevanceFieldEnum)[keyof typeof SessionOrderByRelevanceFieldEnum]


export const SupplierOrderByRelevanceFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  ruc: 'ruc',
  email: 'email',
  phone: 'phone',
  whatsapp: 'whatsapp',
  address: 'address',
  city: 'city',
  notes: 'notes',
  paymentTerms: 'paymentTerms',
  contacts: 'contacts'
} as const

export type SupplierOrderByRelevanceFieldEnum = (typeof SupplierOrderByRelevanceFieldEnum)[keyof typeof SupplierOrderByRelevanceFieldEnum]


export const PurchaseOrderByRelevanceFieldEnum = {
  id: 'id',
  purchaseNumber: 'purchaseNumber',
  invoiceNumber: 'invoiceNumber',
  supplierId: 'supplierId',
  status: 'status',
  paymentStatus: 'paymentStatus',
  notes: 'notes',
  createdBy: 'createdBy'
} as const

export type PurchaseOrderByRelevanceFieldEnum = (typeof PurchaseOrderByRelevanceFieldEnum)[keyof typeof PurchaseOrderByRelevanceFieldEnum]


export const PurchaseItemOrderByRelevanceFieldEnum = {
  id: 'id',
  purchaseId: 'purchaseId',
  productId: 'productId',
  productName: 'productName',
  productSku: 'productSku',
  notes: 'notes'
} as const

export type PurchaseItemOrderByRelevanceFieldEnum = (typeof PurchaseItemOrderByRelevanceFieldEnum)[keyof typeof PurchaseItemOrderByRelevanceFieldEnum]


export const StockMovementOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  type: 'type',
  reason: 'reason',
  reference: 'reference',
  unit: 'unit',
  notes: 'notes',
  userId: 'userId'
} as const

export type StockMovementOrderByRelevanceFieldEnum = (typeof StockMovementOrderByRelevanceFieldEnum)[keyof typeof StockMovementOrderByRelevanceFieldEnum]


export const ReturnOrderOrderByRelevanceFieldEnum = {
  id: 'id',
  returnNumber: 'returnNumber',
  orderId: 'orderId',
  customerId: 'customerId',
  customerName: 'customerName',
  status: 'status',
  reason: 'reason',
  createdBy: 'createdBy'
} as const

export type ReturnOrderOrderByRelevanceFieldEnum = (typeof ReturnOrderOrderByRelevanceFieldEnum)[keyof typeof ReturnOrderOrderByRelevanceFieldEnum]


export const ReturnItemOrderByRelevanceFieldEnum = {
  id: 'id',
  returnId: 'returnId',
  productId: 'productId',
  productName: 'productName',
  condition: 'condition'
} as const

export type ReturnItemOrderByRelevanceFieldEnum = (typeof ReturnItemOrderByRelevanceFieldEnum)[keyof typeof ReturnItemOrderByRelevanceFieldEnum]


export const CashSessionOrderByRelevanceFieldEnum = {
  id: 'id',
  openedBy: 'openedBy',
  notes: 'notes',
  status: 'status',
  closedBy: 'closedBy'
} as const

export type CashSessionOrderByRelevanceFieldEnum = (typeof CashSessionOrderByRelevanceFieldEnum)[keyof typeof CashSessionOrderByRelevanceFieldEnum]


export const CashMovementOrderByRelevanceFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  type: 'type',
  category: 'category',
  description: 'description',
  createdBy: 'createdBy'
} as const

export type CashMovementOrderByRelevanceFieldEnum = (typeof CashMovementOrderByRelevanceFieldEnum)[keyof typeof CashMovementOrderByRelevanceFieldEnum]

